---
swagger: 2.0
info:
  title: Summit API
  description: An API that gives information about the Red Hat Summit.
  version: 2.0.0
paths:
  /location:
    get:
      summary: Get Next RH Summit Location
      description: 'Get the location of the next RedHat Summit '
      operationId: GetLocation
      responses:
        200:
          description: OK
  /timeframe:
    get:
      summary: Get Next RH Summit Timeframe
      description: Get the timeframe of the next RedHat Summit.
      operationId: GetTimeframe
      responses:
        200:
          description: OK
  /participants:
    get:
      summary: Get all participants
      description: Get a list of all participants
      operationId: GetParticipants
      responses:
        200:
          description: OK
securityDefinitions:
  oidc:
    type: oauth2
    flow: accessCode
    scopes:
      openid: Get an OpenID Connect token
security:
- oidc:
  - openid
